// <auto-generated />
using System;
using EventosUTNapp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EventosUTNapp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250523184111_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Certificado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechaemision");

                    b.Property<int>("InscripcionId")
                        .HasColumnType("integer")
                        .HasColumnName("inscripcionid");

                    b.Property<string>("UrlCertificado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("urlcertificado");

                    b.HasKey("Id");

                    b.HasIndex("InscripcionId")
                        .IsUnique();

                    b.ToTable("certificados");
                });

            modelBuilder.Entity("EventosUTNapp.Models.EstadoInscripcion", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("estadosinscripcion");
                });

            modelBuilder.Entity("EventosUTNapp.Models.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("Lugar")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lugar");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<short>("TipoEventoId")
                        .HasColumnType("smallint")
                        .HasColumnName("tipoeventoid");

                    b.HasKey("Id");

                    b.HasIndex("TipoEventoId");

                    b.ToTable("eventos");
                });

            modelBuilder.Entity("EventosUTNapp.Models.EventoPonente", b =>
                {
                    b.Property<int>("EventoId")
                        .HasColumnType("integer")
                        .HasColumnName("eventoid");

                    b.Property<int>("PonenteId")
                        .HasColumnType("integer")
                        .HasColumnName("ponenteid");

                    b.HasKey("EventoId", "PonenteId");

                    b.HasIndex("PonenteId");

                    b.ToTable("eventoponentes");
                });

            modelBuilder.Entity("EventosUTNapp.Models.MetodoPago", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("metodospago");
                });

            modelBuilder.Entity("EventosUTNapp.Models.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechapago");

                    b.Property<int>("InscripcionId")
                        .HasColumnType("integer")
                        .HasColumnName("inscripcionid");

                    b.Property<short>("MetodoPagoId")
                        .HasColumnType("smallint")
                        .HasColumnName("metodopagoid");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric")
                        .HasColumnName("monto");

                    b.HasKey("Id");

                    b.HasIndex("InscripcionId");

                    b.HasIndex("MetodoPagoId");

                    b.ToTable("pagos");
                });

            modelBuilder.Entity("EventosUTNapp.Models.Participante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("apellido");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.ToTable("participantes");
                });

            modelBuilder.Entity("EventosUTNapp.Models.Ponente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("apellido");

                    b.Property<string>("Biografia")
                        .HasColumnType("text")
                        .HasColumnName("biografia");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("ponentes");
                });

            modelBuilder.Entity("EventosUTNapp.Models.Sala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("integer")
                        .HasColumnName("capacidad");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("text")
                        .HasColumnName("ubicacion");

                    b.HasKey("Id");

                    b.ToTable("salas");
                });

            modelBuilder.Entity("EventosUTNapp.Models.Sesion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EventoId")
                        .HasColumnType("integer")
                        .HasColumnName("eventoid");

                    b.Property<DateTime>("HoraFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("horafin");

                    b.Property<DateTime>("HoraInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("horainicio");

                    b.Property<int>("SalaId")
                        .HasColumnType("integer")
                        .HasColumnName("salaid");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.HasIndex("SalaId");

                    b.ToTable("sesiones");
                });

            modelBuilder.Entity("EventosUTNapp.Models.TipoEvento", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("tipoeventos");
                });

            modelBuilder.Entity("Inscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("EstadoId")
                        .HasColumnType("smallint")
                        .HasColumnName("estadoid");

                    b.Property<int>("EventoId")
                        .HasColumnType("integer")
                        .HasColumnName("eventoid");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechainscripcion");

                    b.Property<int>("ParticipanteId")
                        .HasColumnType("integer")
                        .HasColumnName("participanteid");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.HasIndex("EventoId");

                    b.HasIndex("ParticipanteId");

                    b.ToTable("inscripciones");
                });

            modelBuilder.Entity("Certificado", b =>
                {
                    b.HasOne("Inscripcion", "Inscripcion")
                        .WithOne("Certificado")
                        .HasForeignKey("Certificado", "InscripcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inscripcion");
                });

            modelBuilder.Entity("EventosUTNapp.Models.Evento", b =>
                {
                    b.HasOne("EventosUTNapp.Models.TipoEvento", "TipoEvento")
                        .WithMany("Eventos")
                        .HasForeignKey("TipoEventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoEvento");
                });

            modelBuilder.Entity("EventosUTNapp.Models.EventoPonente", b =>
                {
                    b.HasOne("EventosUTNapp.Models.Evento", "Evento")
                        .WithMany("EventoPonentes")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventosUTNapp.Models.Ponente", "Ponente")
                        .WithMany("EventoPonentes")
                        .HasForeignKey("PonenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");

                    b.Navigation("Ponente");
                });

            modelBuilder.Entity("EventosUTNapp.Models.Pago", b =>
                {
                    b.HasOne("Inscripcion", "Inscripcion")
                        .WithMany("Pagos")
                        .HasForeignKey("InscripcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventosUTNapp.Models.MetodoPago", "MetodoPago")
                        .WithMany("Pagos")
                        .HasForeignKey("MetodoPagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inscripcion");

                    b.Navigation("MetodoPago");
                });

            modelBuilder.Entity("EventosUTNapp.Models.Sesion", b =>
                {
                    b.HasOne("EventosUTNapp.Models.Evento", "Evento")
                        .WithMany("Sesiones")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventosUTNapp.Models.Sala", "Sala")
                        .WithMany()
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("Inscripcion", b =>
                {
                    b.HasOne("EventosUTNapp.Models.EstadoInscripcion", "Estado")
                        .WithMany("Inscripciones")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventosUTNapp.Models.Evento", "Evento")
                        .WithMany("Inscripciones")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventosUTNapp.Models.Participante", "Participante")
                        .WithMany("Inscripciones")
                        .HasForeignKey("ParticipanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Evento");

                    b.Navigation("Participante");
                });

            modelBuilder.Entity("EventosUTNapp.Models.EstadoInscripcion", b =>
                {
                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("EventosUTNapp.Models.Evento", b =>
                {
                    b.Navigation("EventoPonentes");

                    b.Navigation("Inscripciones");

                    b.Navigation("Sesiones");
                });

            modelBuilder.Entity("EventosUTNapp.Models.MetodoPago", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("EventosUTNapp.Models.Participante", b =>
                {
                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("EventosUTNapp.Models.Ponente", b =>
                {
                    b.Navigation("EventoPonentes");
                });

            modelBuilder.Entity("EventosUTNapp.Models.TipoEvento", b =>
                {
                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("Inscripcion", b =>
                {
                    b.Navigation("Certificado");

                    b.Navigation("Pagos");
                });
#pragma warning restore 612, 618
        }
    }
}
